### ISSUE TITLE
[Node registration]: HRGC

### ISSUE THREAD

**Issue by HRGCompany** [suzaku-network/suzaku-operator-boilerplate#1]
Hello,

I would like to become a node operator on Suzaku Fuji. Here is my information:
- Operator Name: HRGC
- Operator Description: Independent Node Operator
- NodeID: NodeID-D5Yi5wt3UuvucM33Q2McSDcvWNrwp84xD
- BLS Public Key: 0x8d719f4f51e711e0ccad9fc0fdb1ab15da3873064a818922d07c7a205aa46e14072bdb1ceed0d4933a17a39ec82e51bf
- BLS Proof of Possession: 0x886a12bce652fd2b7c25216f406c3b2115d92f1422b53b79c3987cbd13ef0e82c0b47f9ea51396d17aaf7557e165e91e12e4b0fd6a45ee318f3ba0113cc586ec72e53fa67d1e0f17e3066cf44df74f6ea513cc093cfb6d9f7984a8c485f17235

My node is already fully sync!

Cheers,
Romain.

**Comment by leopaul36** [comment]
Hi @HRGCompany,

Thanks for your interest in Suzaku! Your node has been added to the validator set :+1:
