### ISSUE TITLE
[Node registration]: Silk Nodes

### ISSUE THREAD

**Issue by Bosco-2019** [suzaku-network/suzaku-operator-boilerplate#2]
### Operator name

Silk Nodes

### Operator description

Silk Nodes pride ourselves on being 100% bare metal, self owned and self hosted validators, running our own infrastructure to validate the chains we are active on.

### NodeID

NodeID-4PW41YoGHcNeJAR88Y8xZwqBh3GEbzP9b

### NodeID

0x8855abc407c369373f21586bf8afa8edb39862163da4aae6f313cde4c4bfe78e46867de18938f7c3944b440d5be15837

### NodeID

0x8e26713c31bb8c9f3439ee642ea786036349638d0c299e69c9e1f9a07b918bd8f484b65546acad4a03e0bf00183ff08912b71c72e6ae890af9b28b2c73c577930cd4ff3b74db0934114b0a31611be7fc37ecd5ae19ad51950dd48d26928a1d97

**Comment by leopaul36** [comment]
Hi @Bosco-2019,

Thanks for your interest in Suzaku! Your node has been added to the validator set 👍

```bash
curl --location --request POST https://api.avax-test.network/ext/bc/P \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"platform.getValidatorsAt",
    "params" :{
        "height": "proposed",
        "subnetID":"22XB5waRLucd7upLoKpJ1R8j5hUDnnTzGc9Z7giEKjPYdu5VDK"
    }
}' | jq
```

```json
[...]
"NodeID-4PW41YoGHcNeJAR88Y8xZwqBh3GEbzP9b": {
      "publicKey": "0x8855abc407c369373f21586bf8afa8edb39862163da4aae6f313cde4c4bfe78e46867de18938f7c3944b440d5be15837",
      "weight": "20"
    },
[...]
```
